#!/bin/bash

CYAN="\033[0;36m" #cyan
YELLOW="\033[1;33m" #yellow

target_text=""
file_pattern="*"
lines_after_match=0

while getopts "p:n:f:" arg; do
  case "$arg" in
    n)
      lines_after_match="${OPTARG}"
      ;;
    f)
      file_pattern="${OPTARG}"
      ;;
    p)
      target_text="${OPTARG}"
      ;;
    *)
      printf "Bad input. Flags are: {n, f, p (required)}"
      exit -1
      ;; 
  esac
done
shift "$((OPTIND-1))"

find . -type f -name "$file_pattern" -print0 | while IFS= read -r -d '' file; do
    if [ $lines_after_match -gt 0 ]; then
        lines="$(grep -i -n -A"${lines_after_match}" "$target_text" "$file")"
    else 
        lines="$(grep -i -n "$target_text" "$file")"
    fi
    
    if [  "$lines" != "" ]; then 
        echo -e "${YELLOW}$file"
        echo -e  "${CYAN}$lines"; 
    fi; 
done